### PR TITLE
Added AXIS_KNOB manipulator.

### PR DESCRIPTION
**Pull request by dpospisil**

### CODE REVIEW

**Comment by tngreene** [comment]
Thank you for bringing this to our attention! Somehow this manipulator does seem to be missing. What you have included is basic changes, but what is really needed in addition to this is a rule added to the updater, because changing an enum mutates .blend file's choices.

So, I'll take the pull request and save some typing and copy and pasting, and I'll add the testing and updating code (since I want the responsibility of everyone's manipulator type getting corrupted on my shoulders, not yours.)

In the future, please create an issue first, like #328, so we can help you with implementing something or warn you if you might be wasting your time. Thank you for this, though!

**Comment by tngreene** [comment]
By now the direction of 314-new-vr-manips branch has changed the UI code dramatically, making the changes to xplane_ui no longer useful. The other stuff, however, is still relevant and thank you for submitting this because it keeps it on the back burner, instead of forgotten entirely.

**Comment by dpospisil** [comment]
Thanks for the update. Next time I will create the issue first as advised. Should I create the issue for this one now?

**Comment by tngreene** [comment]
Although the pull request wasn't merged through the GUI, it was incorporated into XPlane2Blender in 5cc0b767e769. Thank you! Without PRs like this, stuff doesn't get added!

**Pull request closed without merging**
